#!/bin/bash

echo "Build hook running..."

root_versions=(6.18.02 6.20.02)

for v in ${root_versions[@]}; do
    docker build --build-arg ROOT_VERSION="$v" -f $DOCKERFILE_PATH -t $DOCKER_REPO:$v .
done
