#!/bin/bash

echo "Build hook running..."

root_versions=(
    6.08.06
    6.12.06
    6.14.06
    6.18.02
    6.20.02
    latest
)

for i in ${!root_versions[@]}; do
    ver=${root_versions[i]}
    if [[ $ver == latest ]]; then
        docker tag $DOCKER_REPO:${root_versions[i-1]} $DOCKER_REPO:latest
    else
        docker build --build-arg ROOT_VERSION="$ver" -f $DOCKERFILE_PATH -t $DOCKER_REPO:$ver .
    fi
done
